package Ventanas;


import java.awt.Color;
import java.awt.Dimension;
import java.awt.Graphics;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartFrame;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.data.category.DefaultCategoryDataset;

/**
 *
 */
public class Prueba extends javax.swing.JPanel implements Runnable {

    
    boolean stop = false;
    int x = this.getWidth() / 2;
    int y = this.getHeight() / 2;
    
    int x1 = this.getWidth()+ 1;
    int y1 = this.getHeight()+ 1;
    Thread hilo;
    Thread hilo2;
    
  

    public Prueba()  {
        initComponents();
        hilo = new Thread(this);
        hilo2= new Thread(this);
    }

    public void paint(Graphics g) {
      
        setOpaque(false);
        super.paintComponent(g);
        g.setColor(Color.red);
        g.fillOval(x, y, 20, 20);
        g.fillOval(x1, y1, 20, 20);
    }

    public void inicio() {
        hilo.start();
        hilo2.start();
    }
 
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new javax.swing.OverlayLayout(this));
    }// </editor-fold>//GEN-END:initComponents

    @Override
    public void run() {
        try {
            //Movimiento 1
                        while (x<= getWidth() - 400){
                            Thread.sleep(50);
                            x += 5;
                            repaint();
                            }
                        while (x<= getWidth() - 400){
                            Thread.sleep(50);
                            y += 5;
                            repaint();
                            }  
                        while (y < getHeight() - 25) {
                                Thread.sleep(50);
                                y += 5;
                                repaint();
                            }
                        while (x <= getWidth() - 30) {
                                Thread.sleep(50);
                                x += 5;
                                repaint();
                            }
                //Movimiento 2  
                        while (x1<= getWidth() - 30){
                            Thread.sleep(50);
                            x1 += 5;
                            repaint(); 
                            }
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
    }
    
    
    


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
