/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ventanas;

import Clases.DatosSimulacion;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

import java.util.HashMap;
//import java.util.ArrayList;

/**
 *
 * @author DELL
 */
public class RegisterDataMenu extends javax.swing.JFrame implements ActionListener{

    /**
     * Creates new form RegisterDataMenu
     */
    
    
    /**
     * Variables para simulación
     */
    public String poblacionElegida;
    public int cantidadPoblacion, cantidadPersonasInfectadas, tiempoSimulacion, duracionMedia;
    public double tasaInteraccion, probabilidadContagio, tasaRecuperacion, tasaMortalidad, tasaVacunacion;
    
    
    /**
     * Hashmaps de datos con clave String y valor numérico
     */
    HashMap<String, Integer> poblacionMunicipios = new HashMap<String, Integer>();
    HashMap<String, Integer> tiempoSimulacionComunes = new HashMap<String, Integer>();
    HashMap<String, Integer> duracionEnfermedad = new HashMap<String, Integer>();
    HashMap<String, Double> medidasDistanciamiento = new HashMap<String, Double>();
    
    
    public RegisterDataMenu() {
        initComponents();
        this.setLocationRelativeTo(null);
        jButtonAceptar.addActionListener(this);
        
        //Llenamos los hashmaps con los datos correspondientes a cada caso
        llenarHashMapProvincias();
        llenarHashMapTiemposComunes();
        llenarHashMapDuracionEnfermedad();
        llenarHashMapMedidasDistanciamiento();
        
        //Colocamos los datos de los hashmaps en los dropdowns
        insertarDatosComboBoxPoblacionInicial();
        insertarDatosComboBoxTiempoSimulacion();
        insertarDatosComboBoxDuracionEnfermedad();
        insertarDatosComboBoxMedidasDistanciamiento();
    }

    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelTitulo = new javax.swing.JLabel();
        jButtonVolver = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldProbabilidadContagio = new javax.swing.JTextField();
        jTextFieldDuracionEnfermedad = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldTiempoSimulacion = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel7 = new javax.swing.JLabel();
        jComboBoxPoblacionInicial = new javax.swing.JComboBox<>();
        jLabel14 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jTextFieldPersonasInfectadas = new javax.swing.JTextField();
        jComboBoxTiempoSimulacion = new javax.swing.JComboBox<>();
        jButtonAceptar = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jCheckBoxPoblacionInicial = new javax.swing.JCheckBox();
        jCheckBoxPersonasInfectadas = new javax.swing.JCheckBox();
        jButtonSalir = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jComboBoxInteraccion = new javax.swing.JComboBox<>();
        jComboBoxContagio = new javax.swing.JComboBox<>();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        contagio3 = new javax.swing.JRadioButton();
        contagio4 = new javax.swing.JRadioButton();
        contagio2 = new javax.swing.JRadioButton();
        contagio5 = new javax.swing.JRadioButton();
        contagio6 = new javax.swing.JRadioButton();
        recuperacion1 = new javax.swing.JRadioButton();
        contagio1 = new javax.swing.JRadioButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        recuperacion2 = new javax.swing.JRadioButton();
        recuperacion5 = new javax.swing.JRadioButton();
        sinVacuna = new javax.swing.JRadioButton();
        recuperacion6 = new javax.swing.JRadioButton();
        recuperacion4 = new javax.swing.JRadioButton();
        jLabel18 = new javax.swing.JLabel();
        recuperacion3 = new javax.swing.JRadioButton();
        jTextFieldVacunacion = new javax.swing.JTextField();
        jLabelFondo = new javax.swing.JLabel();
        jLabelTiempo = new javax.swing.JLabel();
        jLabelPoblacionCantidad = new javax.swing.JLabel();
        jLabelPoblacion = new javax.swing.JLabel();
        jLabelInfectadas = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setSize(new java.awt.Dimension(1100, 700));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelTitulo.setFont(new java.awt.Font("Tahoma", 2, 36)); // NOI18N
        jLabelTitulo.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTitulo.setText("Datos para la simulación");
        getContentPane().add(jLabelTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 10, 400, -1));

        jButtonVolver.setBackground(new java.awt.Color(0, 0, 153));
        jButtonVolver.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonVolver.setForeground(new java.awt.Color(255, 255, 255));
        jButtonVolver.setText("VOLVER");
        jButtonVolver.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonVolver.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonVolverMouseClicked(evt);
            }
        });
        jButtonVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVolverActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonVolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("6) Cuidados personales de la población:");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 210, 370, 20));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("4) Duración media de la enfermedad:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 480, 350, 20));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Seleccionar municipio:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 130, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Cantidad de personas:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 260, -1, -1));

        jTextFieldProbabilidadContagio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldProbabilidadContagioActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldProbabilidadContagio, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 160, 200, 30));
        getContentPane().add(jTextFieldDuracionEnfermedad, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 540, 150, 30));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("3) Tiempo de simulación:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 350, -1, -1));

        jTextFieldTiempoSimulacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldTiempoSimulacionActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldTiempoSimulacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 420, 150, 30));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Simular a nivel departamental:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Tiempo en días:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 390, -1, -1));

        jSeparator1.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 72, 1100, 10));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("2) Personas inicialmente infectadas:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, -1, -1));

        jComboBoxPoblacionInicial.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jComboBoxPoblacionInicial.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBoxPoblacionInicial.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jComboBoxPoblacionInicial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxPoblacionInicialActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBoxPoblacionInicial, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 160, 150, -1));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("8) Vacunación:");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 530, 260, 20));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("5) Medidas de distanciamiento social:");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 90, 340, 20));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Simular desde paciente 0:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 260, -1, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Predeterminados:");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 390, -1, -1));

        jTextFieldPersonasInfectadas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldPersonasInfectadasActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldPersonasInfectadas, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 290, 150, 30));

        jComboBoxTiempoSimulacion.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jComboBoxTiempoSimulacion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBoxTiempoSimulacion.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().add(jComboBoxTiempoSimulacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 420, 140, -1));

        jButtonAceptar.setBackground(new java.awt.Color(0, 102, 255));
        jButtonAceptar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonAceptar.setForeground(new java.awt.Color(255, 255, 255));
        jButtonAceptar.setText("SIMULAR");
        jButtonAceptar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonAceptar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonAceptarMouseClicked(evt);
            }
        });
        jButtonAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAceptarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonAceptar, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 630, 180, 40));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("1) Población inicial:");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, -1, -1));

        jCheckBoxPoblacionInicial.setBackground(new java.awt.Color(255, 255, 255));
        jCheckBoxPoblacionInicial.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jCheckBoxPoblacionInicial.setText("Cochabamba");
        jCheckBoxPoblacionInicial.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jCheckBoxPoblacionInicial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxPoblacionInicialActionPerformed(evt);
            }
        });
        getContentPane().add(jCheckBoxPoblacionInicial, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, -1, -1));

        jCheckBoxPersonasInfectadas.setBackground(new java.awt.Color(255, 255, 255));
        jCheckBoxPersonasInfectadas.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jCheckBoxPersonasInfectadas.setText("1 persona");
        jCheckBoxPersonasInfectadas.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().add(jCheckBoxPersonasInfectadas, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 290, 140, 30));

        jButtonSalir.setBackground(new java.awt.Color(204, 0, 0));
        jButtonSalir.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonSalir.setForeground(new java.awt.Color(255, 255, 255));
        jButtonSalir.setText("SALIR");
        jButtonSalir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonSalirMouseClicked(evt);
            }
        });
        jButtonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalirActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 20, -1, -1));

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);
        getContentPane().add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 72, 20, 530));

        jSeparator3.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 600, 1100, 20));

        jComboBoxInteraccion.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jComboBoxInteraccion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(jComboBoxInteraccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 540, 140, 20));

        jComboBoxContagio.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jComboBoxContagio.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(jComboBoxContagio, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 160, 160, 30));

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Predeterminados:");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 510, -1, -1));

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Tiempo en días:");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 510, -1, -1));

        contagio3.setText("Cubrirse al toser");
        getContentPane().add(contagio3, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 330, 160, -1));

        contagio4.setText("Lavarse las manos");
        getContentPane().add(contagio4, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 250, 200, -1));

        contagio2.setText("Usar lentes");
        getContentPane().add(contagio2, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 290, 160, -1));

        contagio5.setText("Desinfectar las compras");
        getContentPane().add(contagio5, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 290, 200, -1));

        contagio6.setText("Evitar tocarse el rostro");
        getContentPane().add(contagio6, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 330, 200, -1));

        recuperacion1.setText("Hospitales con equipamiento");
        getContentPane().add(recuperacion1, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 450, 200, -1));

        contagio1.setText("Usar barbijo");
        getContentPane().add(contagio1, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 250, 160, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Medidas predeterminadas:");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 130, -1, -1));

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Tasa de interacción:");
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 130, -1, -1));

        recuperacion2.setText("Centros de aislamiento");
        getContentPane().add(recuperacion2, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 450, 180, -1));

        recuperacion5.setText("Capacitación de personal");
        getContentPane().add(recuperacion5, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 410, 180, -1));

        sinVacuna.setText("Aun no existe vacuna");
        getContentPane().add(sinVacuna, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 560, 160, -1));

        recuperacion6.setText("Trajes de bioseguridad para médicos");
        getContentPane().add(recuperacion6, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 490, -1, -1));

        recuperacion4.setText("Hospitales de 3er nivel");
        getContentPane().add(recuperacion4, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 490, 180, -1));

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("7) Medidas de preparación:");
        getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 370, 260, 20));

        recuperacion3.setText("Personal de salud disponible");
        getContentPane().add(recuperacion3, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 410, 200, -1));

        jTextFieldVacunacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldVacunacionActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldVacunacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 560, 200, 30));

        jLabelFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fondo-azul.jpg"))); // NOI18N
        getContentPane().add(jLabelFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1100, 700));

        jLabelTiempo.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelTiempo.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTiempo.setText("rPRUEBA");
        getContentPane().add(jLabelTiempo, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 350, -1, -1));

        jLabelPoblacionCantidad.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelPoblacionCantidad.setForeground(new java.awt.Color(255, 255, 255));
        jLabelPoblacionCantidad.setText("rPRUEBA");
        getContentPane().add(jLabelPoblacionCantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 90, -1, -1));

        jLabelPoblacion.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelPoblacion.setForeground(new java.awt.Color(255, 255, 255));
        jLabelPoblacion.setText("rPRUEBA");
        getContentPane().add(jLabelPoblacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 90, -1, -1));

        jLabelInfectadas.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelInfectadas.setForeground(new java.awt.Color(255, 255, 255));
        jLabelInfectadas.setText("rPRUEBA");
        getContentPane().add(jLabelInfectadas, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 220, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonVolverMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonVolverMouseClicked
        StartMenu startMenu = new StartMenu();
        startMenu.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButtonVolverMouseClicked

    private void jButtonVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVolverActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonVolverActionPerformed

    private void jTextFieldTiempoSimulacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldTiempoSimulacionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldTiempoSimulacionActionPerformed

    private void jTextFieldPersonasInfectadasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldPersonasInfectadasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldPersonasInfectadasActionPerformed

    private void jButtonAceptarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonAceptarMouseClicked
//        RegisterDataMenu data = new RegisterDataMenu();
//        data.setVisible(true);
//        this.dispose();
    }//GEN-LAST:event_jButtonAceptarMouseClicked

    private void jButtonAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAceptarActionPerformed

        //Siguiente ventana
        ResultMenu result = new ResultMenu();
        Simulacion result1 = new Simulacion();
        
        //Para pasar la informacion a una clase Singleton
        DatosSimulacion datosSimulacion = DatosSimulacion.getDatosSimulacion();
        
        datosSimulacion.setPoblacionElegida(poblacionElegida);
        datosSimulacion.setCantidadPoblacion(cantidadPoblacion);
        datosSimulacion.setCantidadPersonasInfectadas(cantidadPersonasInfectadas);
        datosSimulacion.setTiempoSimulacion(tiempoSimulacion);
        datosSimulacion.setTasaInteraccion(tasaInteraccion);
        datosSimulacion.setProbabilidadContagio(probabilidadContagio);
        datosSimulacion.setTasaRecuperacion(tasaRecuperacion);
        datosSimulacion.setTasaMortalidad(tasaMortalidad);
        datosSimulacion.setDuracionMedia(duracionMedia);
        datosSimulacion.setTasaVacunacion(tasaVacunacion);
        
        result.resultado();
        
        result1.setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_jButtonAceptarActionPerformed

    private void jComboBoxPoblacionInicialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxPoblacionInicialActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxPoblacionInicialActionPerformed

    private void jButtonSalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonSalirMouseClicked
        System.exit(0);
    }//GEN-LAST:event_jButtonSalirMouseClicked

    private void jButtonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonSalirActionPerformed

    private void jTextFieldProbabilidadContagioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldProbabilidadContagioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldProbabilidadContagioActionPerformed

    private void jCheckBoxPoblacionInicialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxPoblacionInicialActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBoxPoblacionInicialActionPerformed

    private void jTextFieldVacunacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldVacunacionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldVacunacionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegisterDataMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegisterDataMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegisterDataMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegisterDataMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegisterDataMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton contagio1;
    private javax.swing.JRadioButton contagio2;
    private javax.swing.JRadioButton contagio3;
    private javax.swing.JRadioButton contagio4;
    private javax.swing.JRadioButton contagio5;
    private javax.swing.JRadioButton contagio6;
    private javax.swing.JButton jButtonAceptar;
    private javax.swing.JButton jButtonSalir;
    private javax.swing.JButton jButtonVolver;
    private javax.swing.JCheckBox jCheckBoxPersonasInfectadas;
    private javax.swing.JCheckBox jCheckBoxPoblacionInicial;
    private javax.swing.JComboBox<String> jComboBoxContagio;
    private javax.swing.JComboBox<String> jComboBoxInteraccion;
    private javax.swing.JComboBox<String> jComboBoxPoblacionInicial;
    private javax.swing.JComboBox<String> jComboBoxTiempoSimulacion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelFondo;
    private javax.swing.JLabel jLabelInfectadas;
    private javax.swing.JLabel jLabelPoblacion;
    private javax.swing.JLabel jLabelPoblacionCantidad;
    private javax.swing.JLabel jLabelTiempo;
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTextField jTextFieldDuracionEnfermedad;
    private javax.swing.JTextField jTextFieldPersonasInfectadas;
    private javax.swing.JTextField jTextFieldProbabilidadContagio;
    private javax.swing.JTextField jTextFieldTiempoSimulacion;
    private javax.swing.JTextField jTextFieldVacunacion;
    private javax.swing.JRadioButton recuperacion1;
    private javax.swing.JRadioButton recuperacion2;
    private javax.swing.JRadioButton recuperacion3;
    private javax.swing.JRadioButton recuperacion4;
    private javax.swing.JRadioButton recuperacion5;
    private javax.swing.JRadioButton recuperacion6;
    private javax.swing.JRadioButton sinVacuna;
    // End of variables declaration//GEN-END:variables

    @Override
    public void actionPerformed(ActionEvent ae) {
        if (ae.getSource()==jButtonAceptar) {
            insertarPoblacionInicial();
            insertarPersonasInicialmenteInfectadas();
            insertarTiempoDeSimulacion();
            
            insertarDuracionEnfermedad();
            insertarTasaInteraccion();
            calcularTasaContagio();
            calcularTasaRecuperacion();
            calcularTasaMortalidad();
            calcularVacunacion();
        }
        
    }
    
    /**
     * Registra los datos de poblacion inicial, tanto en texto como en cantidad
     * Da prioridad al campo de texto, si este se encontrara vacio verifica el checkbox
     */
    public void insertarPoblacionInicial(){
        if (jCheckBoxPoblacionInicial.isSelected()) {
            poblacionElegida = "Cochabamba";
            cantidadPoblacion = 1758000;
        }else{
            poblacionElegida = jComboBoxPoblacionInicial.getSelectedItem().toString();
            cantidadPoblacion = poblacionMunicipios.get(poblacionElegida);
        }
        jLabelPoblacion.setText(poblacionElegida);
        jLabelPoblacionCantidad.setText(String.valueOf(cantidadPoblacion));
    }
    
    /**
     * Registra los datos de la cantidad inicial de infectados
     * Da prioridad al campo de texto, si este se encontrara vacio verifica el checkbox
     */
    public void insertarPersonasInicialmenteInfectadas(){
        if (jCheckBoxPersonasInfectadas.isSelected()) {
            cantidadPersonasInfectadas = 1;
        }else{
            String personasInfectadas = jTextFieldPersonasInfectadas.getText();
            cantidadPersonasInfectadas = Integer.parseInt(personasInfectadas);
             
        }
        jLabelInfectadas.setText(cantidadPersonasInfectadas + " personas");
    }
    
    /**
     * Registra el tiempo en días para la simulación
     * Da prioridad al campo de texto, si este se encontrara vacio verifica el dropdown
     */
    public void insertarTiempoDeSimulacion(){
        String tiempoEnTexto = jComboBoxTiempoSimulacion.getSelectedItem().toString();
        tiempoSimulacion = tiempoSimulacionComunes.get(tiempoEnTexto);
        
        String tiempoEspecifico = jTextFieldTiempoSimulacion.getText();
        if (!tiempoEspecifico.equals("")) {
            tiempoSimulacion = Integer.parseInt(tiempoEspecifico);
        }
        jLabelTiempo.setText(String.valueOf(tiempoSimulacion));
    }
    
    /**
     * Registra la duracion de la enfermedad por cada persona
     * Da prioridad al campo de texto, si este se encontrara vacio verifica el dropdown
     */
    public void insertarDuracionEnfermedad(){
        String duracionEnTexto = jComboBoxInteraccion.getSelectedItem().toString();
        duracionMedia = duracionEnfermedad.get(duracionEnTexto);
        String tiempoEspecifico = jTextFieldDuracionEnfermedad.getText();
        
        if (!tiempoEspecifico.equals("")) {
            duracionMedia = Integer.parseInt(tiempoEspecifico);
        }
    }
    
    /**
     * Calcula la tasa de interaccion a partir de las medidas de distanciamiento social ingresadas por el usuario
     * Da prioridad al campo de texto, si este se encontrara vacio verifica el dropdown
     */
    public void insertarTasaInteraccion(){
        String duracionEnTexto = jComboBoxContagio.getSelectedItem().toString();
        tasaInteraccion = medidasDistanciamiento.get(duracionEnTexto);
        String tiempoEspecifico = jTextFieldProbabilidadContagio.getText();
        
        if (!tiempoEspecifico.equals("")) {
            tasaInteraccion = Integer.parseInt(tiempoEspecifico);
        }
    }
    
    /**
     * Ingresa la tasa de contagio a partir del resultado del médoto calcularCasillasContagio
     */
    public void calcularTasaContagio(){
        int contadorCasillas = 0;
        
        if(contagio1.isSelected()){
            contadorCasillas += 1;
        } 
        if (contagio2.isSelected()) {
            contadorCasillas += 1;
        }
        if (contagio3.isSelected()) {
            contadorCasillas += 1;
        }
        if (contagio4.isSelected()) {
            contadorCasillas += 1;
        }
        if (contagio5.isSelected()) {
            contadorCasillas += 1;
        }
        if (contagio6.isSelected()) {
            contadorCasillas += 1;
        }
        
        probabilidadContagio = calcularCasillasContagio(contadorCasillas);
    }
    
    /**
     * Calcula la tasa de contagio a partir de la cantidad de campos seleccionados por el usuario
     * A mayor cantidad de campos seleccionados, menor es la probabilidad de contagio
     */
    public double calcularCasillasContagio(int casilla){
        switch (casilla) {
            case 0:
                return 0.25;
            case 1:
                return 0.20;
            case 2:
                return 0.15;
            case 3:
                return 0.13;
            case 4:
                return 0.105;
            case 5:
                return 0.09;
            default:
                return 0.05;
        } 
    }
    
    /**
     * Ingresa la tasa de recuperacion a partir del resultado del médoto calcularCasillasContagio
     */
    public void calcularTasaRecuperacion(){
        int contadorCasillas = 0;
        
        if(recuperacion1.isSelected()){
            contadorCasillas += 1;
        } 
        if (recuperacion2.isSelected()) {
            contadorCasillas += 1;
        }
        if (sinVacuna.isSelected()) {
            contadorCasillas += 1;
        }
        if (recuperacion4.isSelected()) {
            contadorCasillas += 1;
        }
        if (recuperacion5.isSelected()) {
            contadorCasillas += 1;
        }
        if (recuperacion6.isSelected()) {
            contadorCasillas += 1;
        }
        
        tasaRecuperacion = calcularCasillasRecuperacion(contadorCasillas);
    }
    
    /**
     * Calcula la tasa de recuperacion a partir de la cantidad de campos seleccionados por el usuario
     * A mayor cantidad de campos seleccionados, mayor es la probabilidad de recuperación
     */
    public double calcularCasillasRecuperacion(int casilla){
        switch (casilla) {
            case 0:
                return 0.65;
            case 1:
                return 0.70;
            case 2:
                return 0.75;
            case 3:
                return 0.80;
            case 4:
                return 0.85;
            case 5:
                return 0.90;
            default:
                return 0.95;
        } 
    }
    
    public void calcularTasaMortalidad(){
        tasaMortalidad = 1 - tasaRecuperacion;
    }
    
    private void calcularVacunacion(){
        if(sinVacuna.isSelected()){
            tasaVacunacion = 0;
        }
        else{
            String vacunacion = jTextFieldVacunacion.getText();
            tasaVacunacion = Double.parseDouble(vacunacion);
        }
    }
    
    /**
     * Llenan los combobox mediante los hashmaps de cada elemento
     */
    public void insertarDatosComboBoxPoblacionInicial(){
        jComboBoxPoblacionInicial.removeAllItems();
        for (String i : poblacionMunicipios.keySet()) {
            jComboBoxPoblacionInicial.addItem(i);
        }
    }
    
    public void insertarDatosComboBoxTiempoSimulacion(){
        jComboBoxTiempoSimulacion.removeAllItems();
        for (String i : tiempoSimulacionComunes.keySet()) {
            jComboBoxTiempoSimulacion.addItem(i);
        }
    }
    
    public void insertarDatosComboBoxDuracionEnfermedad(){
        jComboBoxInteraccion.removeAllItems();
        for (String i : duracionEnfermedad.keySet()) {
            jComboBoxInteraccion.addItem(i);
        }
    }
    
    public void insertarDatosComboBoxMedidasDistanciamiento(){
        jComboBoxContagio.removeAllItems();
        for (String i : medidasDistanciamiento.keySet()) {
            jComboBoxContagio.addItem(i);
        }
    }
    
    
    /**
     * Llenan los hashmaps con llave valor según lo requerido
     */
    public void llenarHashMapProvincias(){
        poblacionMunicipios.put("Arani", 18444);
        poblacionMunicipios.put("Arque", 20630);
        poblacionMunicipios.put("Ayopaya", 54408);
        poblacionMunicipios.put("Bolívar", 7279);
        poblacionMunicipios.put("Campero", 35763);
        poblacionMunicipios.put("Capinota", 6527);
        poblacionMunicipios.put("Carrasco", 149729);
        poblacionMunicipios.put("Cercado", 630587);
        poblacionMunicipios.put("Chapare", 262845);
        poblacionMunicipios.put("Esteban Arce", 37152);
        poblacionMunicipios.put("Germán Jordán", 34342);
        poblacionMunicipios.put("Mizque", 35586);
        poblacionMunicipios.put("Punata", 54409);
        poblacionMunicipios.put("Quillacollo", 335393);
        poblacionMunicipios.put("Tapacarí", 24595);
        poblacionMunicipios.put("Tiraque", 41954);
    }
    
    public void llenarHashMapTiemposComunes(){
        tiempoSimulacionComunes.put("Un mes", 30);
        tiempoSimulacionComunes.put("Dos meses", 60);
        tiempoSimulacionComunes.put("Seis meses", 182);
        tiempoSimulacionComunes.put("Un año", 364);
        tiempoSimulacionComunes.put("Un año y seis meses", 546);
        tiempoSimulacionComunes.put("Dos años", 728);
    }
    
    public void llenarHashMapDuracionEnfermedad(){
        duracionEnfermedad.put("Una semana", 7);
        duracionEnfermedad.put("Dos semanas", 14);
        duracionEnfermedad.put("Tres semanas", 21);
        duracionEnfermedad.put("Cuatro semanas", 28);
    }
    
    public void llenarHashMapMedidasDistanciamiento(){
        medidasDistanciamiento.put("Sin cuarentena", 2.5);
        medidasDistanciamiento.put("Cuarentena dinámica", 1.6);
        medidasDistanciamiento.put("Cuarentena mixta", 1.42);
        medidasDistanciamiento.put("Cuarentena rígida", 1.4);
    }
}
