/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ventanas;

/**
 *
 * @author HOME
 */


import Clases.DatosSimulacion;
import Clases.ResultadosSimulacion;
import java.util.ArrayList; // import the ArrayList class
import java.util.HashMap;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import net.sf.jasperreports.engine.JREmptyDataSource;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JasperViewer;
    import org.jfree.chart.ChartFactory;
    import org.jfree.chart.ChartFrame;
import org.jfree.chart.ChartPanel;
    import org.jfree.chart.JFreeChart;
    import org.jfree.chart.plot.PlotOrientation;
    import org.jfree.data.category.DefaultCategoryDataset;

public class ResultMenu extends javax.swing.JFrame {

    /**
     * Creates new form ResultMenu
     */
     private String fechaInicioo, fechaFinn, inicialmenteInfectadoss, tiempoSimulacionn, distanciamientoo, totalContagiadoss, totalFallecidoss, recuperadoss;
  
     
     public ResultMenu() {
        initComponents();
        this.setLocationRelativeTo(null);
        //modeloSIRF();
    }
     
     

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    double poblacion_total, personasInfectadas, tiempo, tasaInter, probabilidadCon, tasaRec, tasaMor, duracionMed, tasaVacunacion = 0.01;
    double susceptibles, infectados, R, F, vacunados;
    int totalContagiados, totalNoAfectados;
    

    ArrayList<String> contagiadosDia = new ArrayList<>(); // Create an ArrayList object
    ArrayList<String> infectadosDia = new ArrayList<>();
    ArrayList<String> recuperadosDia = new ArrayList<>();
    ArrayList<String> fallecidosDia = new ArrayList<>();
    ArrayList<String> noAfectadosDia = new ArrayList<>();
    ArrayList<String> vacunadosDia = new ArrayList<>();
    
    ArrayList<Integer> dias = new ArrayList<>();
   
    //curva
    DefaultCategoryDataset curvainfectados = new DefaultCategoryDataset();
    DefaultCategoryDataset curvarecu = new DefaultCategoryDataset();
    DefaultCategoryDataset curvafallecidos = new DefaultCategoryDataset();
    
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JLabelPoblacion = new javax.swing.JLabel();
        JLabelPersonasInfectadas = new javax.swing.JLabel();
        JLabelTiempo = new javax.swing.JLabel();
        jLabelInteraccion = new javax.swing.JLabel();
        jLabelContagio = new javax.swing.JLabel();
        jLabeltasaRecuperacion = new javax.swing.JLabel();
        jLabeltasaMortalidad = new javax.swing.JLabel();
        jLabelDuracion = new javax.swing.JLabel();
        jLabelVacunacion = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabelRecuperados = new javax.swing.JLabel();
        jLabelInfectadas = new javax.swing.JLabel();
        jLabelSusceptibles = new javax.swing.JLabel();
        jLabelContagiados = new javax.swing.JLabel();
        jButtonVolver = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabelTitulo = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabelFallecidos = new javax.swing.JLabel();
        jButtonSalir = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        jButtonAceptar = new javax.swing.JButton();
        jLabelTitulo1 = new javax.swing.JLabel();
        jLabelTitulo2 = new javax.swing.JLabel();
        jLabelTitulo4 = new javax.swing.JLabel();
        jLabelTitulo5 = new javax.swing.JLabel();
        jRadioButtonSegunda = new javax.swing.JRadioButton();
        jRadioButtonTercera = new javax.swing.JRadioButton();
        jRadioButtonCuarta = new javax.swing.JRadioButton();
        jRadioButtonPrimera = new javax.swing.JRadioButton();
        jButton3 = new javax.swing.JButton();
        jLabelTotalContagiadoss = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabelTotalFallecidoss = new javax.swing.JLabel();
        jLabelRecuperadoss = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabelFechaInicioo = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabelFechaFinn = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabelTiempoSimulacionn = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabelInicialmenteInfectadoss = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        jLabelDistanciamientoo = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jComboBoxDia = new javax.swing.JComboBox<>();
        jLabelTitulo3 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        jLabelVacunados = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        curva = new javax.swing.JButton();
        curvarecuperados = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();

        JLabelPoblacion.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        JLabelPoblacion.setForeground(new java.awt.Color(255, 255, 255));
        JLabelPoblacion.setText("hola");

        JLabelPersonasInfectadas.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        JLabelPersonasInfectadas.setForeground(new java.awt.Color(255, 255, 255));
        JLabelPersonasInfectadas.setText("hola");

        JLabelTiempo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        JLabelTiempo.setForeground(new java.awt.Color(255, 255, 255));
        JLabelTiempo.setText("hola");

        jLabelInteraccion.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelInteraccion.setForeground(new java.awt.Color(255, 255, 255));
        jLabelInteraccion.setText("jLabel2");

        jLabelContagio.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelContagio.setForeground(new java.awt.Color(255, 255, 255));
        jLabelContagio.setText("jLabel2");

        jLabeltasaRecuperacion.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabeltasaRecuperacion.setForeground(new java.awt.Color(255, 255, 255));
        jLabeltasaRecuperacion.setText("jLabel2");

        jLabeltasaMortalidad.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabeltasaMortalidad.setForeground(new java.awt.Color(255, 255, 255));
        jLabeltasaMortalidad.setText("jLabel2");

        jLabelDuracion.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelDuracion.setForeground(new java.awt.Color(255, 255, 255));
        jLabelDuracion.setText("jLabel2");

        jLabelVacunacion.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelVacunacion.setForeground(new java.awt.Color(255, 255, 255));
        jLabelVacunacion.setText("jLabel2");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Poblacion");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1100, 700));
        setMinimumSize(new java.awt.Dimension(1100, 700));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(1100, 700));
        setSize(new java.awt.Dimension(1100, 700));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Poblacion Total Contagiada:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 320, 270, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Poblacion Infectada:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 360, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Poblacion Total Fallecida:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 440, -1, -1));

        jLabelRecuperados.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelRecuperados.setForeground(new java.awt.Color(255, 255, 255));
        jLabelRecuperados.setText("hola");
        getContentPane().add(jLabelRecuperados, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 400, -1, -1));

        jLabelInfectadas.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelInfectadas.setForeground(new java.awt.Color(255, 255, 255));
        jLabelInfectadas.setText("hola");
        getContentPane().add(jLabelInfectadas, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 360, -1, -1));

        jLabelSusceptibles.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelSusceptibles.setForeground(new java.awt.Color(255, 255, 255));
        jLabelSusceptibles.setText("hola");
        getContentPane().add(jLabelSusceptibles, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 520, -1, -1));

        jLabelContagiados.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelContagiados.setForeground(new java.awt.Color(255, 255, 255));
        jLabelContagiados.setText("hola");
        getContentPane().add(jLabelContagiados, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 320, -1, -1));

        jButtonVolver.setBackground(new java.awt.Color(0, 0, 153));
        jButtonVolver.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonVolver.setForeground(new java.awt.Color(255, 255, 255));
        jButtonVolver.setText("VOLVER");
        jButtonVolver.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButtonVolver.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonVolverMouseClicked(evt);
            }
        });
        jButtonVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVolverActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonVolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 100, 30));

        jSeparator1.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 72, 1100, -1));

        jLabelTitulo.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabelTitulo.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTitulo.setText("de Covid-19");
        getContentPane().add(jLabelTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 120, 160, 30));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Poblacion no Afectada:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 520, -1, -1));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Poblacion Total Recuperada:");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 400, -1, -1));

        jLabelFallecidos.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelFallecidos.setForeground(new java.awt.Color(255, 255, 255));
        jLabelFallecidos.setText("hola");
        getContentPane().add(jLabelFallecidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 440, -1, -1));

        jButtonSalir.setBackground(new java.awt.Color(204, 0, 0));
        jButtonSalir.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonSalir.setForeground(new java.awt.Color(255, 255, 255));
        jButtonSalir.setText("SALIR");
        jButtonSalir.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButtonSalir.setMaximumSize(new java.awt.Dimension(89, 23));
        jButtonSalir.setMinimumSize(new java.awt.Dimension(89, 23));
        jButtonSalir.setPreferredSize(new java.awt.Dimension(89, 23));
        jButtonSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonSalirMouseClicked(evt);
            }
        });
        jButtonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalirActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 20, 80, 30));

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);
        getContentPane().add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 72, 20, 560));

        jButtonAceptar.setBackground(new java.awt.Color(0, 102, 255));
        jButtonAceptar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonAceptar.setForeground(new java.awt.Color(255, 255, 255));
        jButtonAceptar.setText("ACEPTAR");
        jButtonAceptar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButtonAceptar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonAceptarMouseClicked(evt);
            }
        });
        jButtonAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAceptarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonAceptar, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 190, 100, 30));

        jLabelTitulo1.setFont(new java.awt.Font("Tahoma", 2, 36)); // NOI18N
        jLabelTitulo1.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTitulo1.setText("COMPARACIÓN DE DATOS  COVID-19");
        getContentPane().add(jLabelTitulo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 20, 610, -1));

        jLabelTitulo2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabelTitulo2.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTitulo2.setText("Cochabamba ");
        getContentPane().add(jLabelTitulo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 120, 180, 40));

        jLabelTitulo4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabelTitulo4.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTitulo4.setText("Datos Reales del departamento de");
        getContentPane().add(jLabelTitulo4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 80, 430, 40));

        jLabelTitulo5.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabelTitulo5.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTitulo5.setText("Resultado de la simulación");
        getContentPane().add(jLabelTitulo5, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 90, 330, -1));

        buttonGroup1.add(jRadioButtonSegunda);
        jRadioButtonSegunda.setText("Segunda etapa");
        getContentPane().add(jRadioButtonSegunda, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 260, 160, -1));

        buttonGroup1.add(jRadioButtonTercera);
        jRadioButtonTercera.setText("Tercera etapa");
        getContentPane().add(jRadioButtonTercera, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 290, 160, -1));

        buttonGroup1.add(jRadioButtonCuarta);
        jRadioButtonCuarta.setText("Cuarta etapa ");
        getContentPane().add(jRadioButtonCuarta, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 320, 160, -1));

        buttonGroup1.add(jRadioButtonPrimera);
        jRadioButtonPrimera.setText("Primera etapa");
        jRadioButtonPrimera.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jRadioButtonPrimera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonPrimeraActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioButtonPrimera, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, 160, -1));

        jButton3.setBackground(new java.awt.Color(0, 102, 255));
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Seleccionar");
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 370, 110, -1));

        jLabelTotalContagiadoss.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelTotalContagiadoss.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTotalContagiadoss.setText("-");
        getContentPane().add(jLabelTotalContagiadoss, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 430, 130, 20));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Poblacion Total Contagiada:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 430, 260, 20));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Poblacion Total Fallecida:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 470, 240, -1));

        jLabelTotalFallecidoss.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelTotalFallecidoss.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTotalFallecidoss.setText("-");
        getContentPane().add(jLabelTotalFallecidoss, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 470, 140, 20));

        jLabelRecuperadoss.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelRecuperadoss.setForeground(new java.awt.Color(255, 255, 255));
        jLabelRecuperadoss.setText("-");
        getContentPane().add(jLabelRecuperadoss, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 510, 130, 20));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Poblacion Recuperados:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 510, 230, 20));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Fecha Inicio:");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 220, 110, 20));

        jLabelFechaInicioo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelFechaInicioo.setForeground(new java.awt.Color(255, 255, 255));
        jLabelFechaInicioo.setText("-");
        getContentPane().add(jLabelFechaInicioo, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 220, 120, 20));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Fecha Fin:");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 250, 80, -1));

        jLabelFechaFinn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelFechaFinn.setForeground(new java.awt.Color(255, 255, 255));
        jLabelFechaFinn.setText("-");
        getContentPane().add(jLabelFechaFinn, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 250, 120, 20));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Duracion de Simulacion:");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 280, -1, -1));

        jLabelTiempoSimulacionn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelTiempoSimulacionn.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTiempoSimulacionn.setText("-");
        getContentPane().add(jLabelTiempoSimulacionn, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 280, 120, 20));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Inicialmente Infectadas:");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 310, 170, 20));

        jLabelInicialmenteInfectadoss.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelInicialmenteInfectadoss.setForeground(new java.awt.Color(255, 255, 255));
        jLabelInicialmenteInfectadoss.setText("-");
        getContentPane().add(jLabelInicialmenteInfectadoss, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 310, 120, 20));

        jButton6.setBackground(new java.awt.Color(0, 102, 255));
        jButton6.setForeground(new java.awt.Color(255, 255, 255));
        jButton6.setText("CURVA FALLECIDOS");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 570, 170, 40));

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Distanciamiento:");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 340, -1, -1));

        jLabelDistanciamientoo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelDistanciamientoo.setForeground(new java.awt.Color(255, 255, 255));
        jLabelDistanciamientoo.setText("-");
        getContentPane().add(jLabelDistanciamientoo, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 340, 150, 20));
        getContentPane().add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 630, 1100, 20));

        jComboBoxDia.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBoxDia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxDiaActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBoxDia, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 190, 90, 30));

        jLabelTitulo3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelTitulo3.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTitulo3.setText("Escoger día de simulación:");
        getContentPane().add(jLabelTitulo3, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 190, 250, -1));

        jButton2.setBackground(new java.awt.Color(0, 102, 255));
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("GRAFICAR");
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 580, 120, 40));

        jButton1.setBackground(new java.awt.Color(0, 102, 255));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("GRAFICAR");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 240, 110, 30));

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Poblacion Total Vacunada:");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 480, -1, -1));

        jLabelVacunados.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelVacunados.setForeground(new java.awt.Color(255, 255, 255));
        jLabelVacunados.setText("hola");
        getContentPane().add(jLabelVacunados, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 480, -1, -1));

        jButton4.setBackground(new java.awt.Color(0, 102, 255));
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("GRAFICAR");
        jButton4.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton4MouseClicked(evt);
            }
        });
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 580, 120, 40));

        jButton5.setBackground(new java.awt.Color(0, 102, 255));
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setText("GRAFICAR COMPARACIÓN");
        jButton5.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButton5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton5MouseClicked(evt);
            }
        });
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 640, 220, 40));

        jButton7.setBackground(new java.awt.Color(0, 102, 255));
        jButton7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton7.setForeground(new java.awt.Color(255, 255, 255));
        jButton7.setText("REPORTE FINAL");
        jButton7.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButton7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton7MouseClicked(evt);
            }
        });
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 640, 220, 40));

        curva.setBackground(new java.awt.Color(0, 102, 255));
        curva.setForeground(new java.awt.Color(255, 255, 255));
        curva.setText("CURVA INFECTADOS");
        curva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                curvaActionPerformed(evt);
            }
        });
        getContentPane().add(curva, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 570, 170, 40));

        curvarecuperados.setBackground(new java.awt.Color(0, 102, 255));
        curvarecuperados.setForeground(new java.awt.Color(255, 255, 255));
        curvarecuperados.setText("CURVA RECUPERADOS");
        curvarecuperados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                curvarecuperadosActionPerformed(evt);
            }
        });
        getContentPane().add(curvarecuperados, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 570, 180, 40));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fondo-azul.jpg"))); // NOI18N
        jLabel11.setText("jLabel11");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, -10, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
        double tasaInteraccion = tasaInter;
        double probab = probabilidadCon;
        double tasaR = tasaRec;
        double tasaM = tasaMor;
        
        JLabelPoblacion.setText(Math.round(poblacion_total) + "");
        JLabelPersonasInfectadas.setText(Math.round(personasInfectadas) + "");
        JLabelTiempo.setText(Math.round(tiempo) + " días");
        jLabelInteraccion.setText(Math.round(tasaInteraccion) + " personas");
        jLabelContagio.setText(Math.round(probab*100) + " %");
        jLabeltasaRecuperacion.setText(Math.round(tasaR*100) + " %");
        jLabeltasaMortalidad.setText(Math.round(tasaM*100) + " %");
        jLabelDuracion.setText(Math.round(duracionMed) + " dias");
        if(tasaVacunacion != 0){
            jLabelVacunacion.setText(tasaVacunacion*100 + " %");
        }
        else{
            jLabelVacunacion.setText("No existe");
        }
        
        int nroContagiados = (int)Math.round(infectados) + (int)Math.round(R) + (int)Math.round(F);
        int nroSusceptibles = (int)Math.round(poblacion_total) - nroContagiados;

        totalContagiados = nroContagiados;
        totalNoAfectados = nroSusceptibles;
        
        jLabelSusceptibles.setText(nroSusceptibles + "");
        jLabelContagiados.setText(nroContagiados + "");
        jLabelRecuperados.setText(Math.round(R) + "");
        jLabelFallecidos.setText(Math.round(F) + "");
        jLabelInfectadas.setText(Math.round(infectados) + "");
        jLabelVacunados.setText(Math.round(vacunados) + "");
        
        setResultadosFinales(nroContagiados, nroSusceptibles);
    }//GEN-LAST:event_formWindowActivated

    
    private void jButtonVolverMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonVolverMouseClicked
        StartMenu startMenu = new StartMenu();
        startMenu.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButtonVolverMouseClicked

    private void jButtonVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVolverActionPerformed
        // TODO add your handling code here:
        Simulacion register = new Simulacion();
        register.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButtonVolverActionPerformed

    private void jButtonSalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonSalirMouseClicked
        System.exit(0);
    }//GEN-LAST:event_jButtonSalirMouseClicked

    private void jButtonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonSalirActionPerformed

    private void jButtonAceptarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonAceptarMouseClicked
        //        RegisterDataMenu data = new RegisterDataMenu();
        //        data.setVisible(true);
        //        this.dispose();
    }//GEN-LAST:event_jButtonAceptarMouseClicked

    private void jButtonAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAceptarActionPerformed
        buscarDia();
    }//GEN-LAST:event_jButtonAceptarActionPerformed

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        // TODO add your handling code here: AQUI OTROOO
        int cantidad1=Integer.parseInt(jLabelTotalContagiadoss.getText());
        int cantidad2=Integer.parseInt(jLabelTotalFallecidoss.getText());
        int cantidad3=Integer.parseInt(jLabelRecuperadoss.getText());
        //  int cantidad3=Integer.parseInt(txt3.getText());
        try{
            DefaultCategoryDataset ds=new DefaultCategoryDataset();

            ds.addValue(cantidad1, "Poblacion Total Contagiada", "");
            ds.addValue(cantidad3,"Poblacion Total Recuperada", "");
            ds.addValue(cantidad2, "Poblacion total fallecida", "");
            
            //ds.addValue(cantidad3,"Fallecido", "");

            JFreeChart jf=ChartFactory.createBarChart3D("DATOS REALES DEL COVID-19","","Personas",ds,PlotOrientation.VERTICAL,true,true,true);
            ChartFrame f=new ChartFrame("Simulador", jf);
            f.setSize(600,600);
            f.setLocationRelativeTo(null);
            f.setVisible(true);
        }catch (Exception e){
            System.out.println("error "+e);
        }
    }//GEN-LAST:event_jButton2MouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:AQUI SIIIIIIIIIII
        int cantidad1=Integer.parseInt(jLabelContagiados.getText());
        int cantidad2=Integer.parseInt(jLabelInfectadas.getText());
        int cantidad3=Integer.parseInt(jLabelRecuperados.getText());
        int cantidad4=Integer.parseInt(jLabelFallecidos.getText());
        int cantidad5=Integer.parseInt(jLabelVacunados.getText());
        try{
            DefaultCategoryDataset ds=new DefaultCategoryDataset();

            ds.addValue(cantidad1, "Poblacion Total Contagiados", "");
            ds.addValue(cantidad3, "Poblacion Total Recuperados", "");
            ds.addValue(cantidad4, "Poblacion Total Fallecidos", "");
            ds.addValue(cantidad2, "Poblacion Total Infectados", "");
            ds.addValue(cantidad5, "Vacunados", "");

            JFreeChart jf=ChartFactory.createBarChart3D("DATOS DE SIMULACION DEL COVID-19","","Personas",ds,PlotOrientation.VERTICAL,true,true,true);
            ChartFrame f=new ChartFrame("Simulador", jf);
            f.setSize(600,600);
            f.setLocationRelativeTo(null);
            f.setVisible(true);
        }catch (Exception e){
            System.out.println("error "+e);
        }
    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jRadioButtonPrimeraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonPrimeraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButtonPrimeraActionPerformed

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked
         setFechaOEvento();
        if(fechaFinn != null)
            setCampos();
    }//GEN-LAST:event_jButton3MouseClicked

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4MouseClicked

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton5MouseClicked
        // TODO add your handling code here:AQUI SIIIIIIIIIII
        int cantidad1=Integer.parseInt(jLabelContagiados.getText());
        int cantidad2=Integer.parseInt(jLabelInfectadas.getText());
        int cantidad3=Integer.parseInt(jLabelRecuperados.getText());
        int cantidad4=Integer.parseInt(jLabelFallecidos.getText());
        int cantidad5=Integer.parseInt(jLabelVacunados.getText());
        int cantidad9=Integer.parseInt(jLabelTotalContagiadoss.getText());
        int cantidad10=Integer.parseInt(jLabelTotalFallecidoss.getText());
        int cantidad11=Integer.parseInt(jLabelRecuperadoss.getText());
        try{
            DefaultCategoryDataset ds=new DefaultCategoryDataset();

            ds.addValue(cantidad9, "(DR)Poblacion Total Contagiada ", "");
            ds.addValue(cantidad1, "(S)Poblacion Total Contagiados", "");
            ds.addValue(cantidad10,"(DR)Poblacion Total Recuperada", "");
            ds.addValue(cantidad3, "(S)Poblacion Total Recuperados", "");
            ds.addValue(cantidad11, "(DR)Poblacion total fallecida", "");
            ds.addValue(cantidad4, "(S)Poblacion Total Fallecidos", "");
            ds.addValue(cantidad2, "(S)Poblacion Total Infectados", "");
            ds.addValue(cantidad5, "(S)Vacunados", "");

            JFreeChart jf=ChartFactory.createBarChart3D("COMPARACION DE DATOS DEL COVID-19","","Personas",ds,PlotOrientation.VERTICAL,true,true,true);
            ChartFrame f=new ChartFrame("Simulador", jf);
            f.setSize(800,600);
            f.setLocationRelativeTo(null);
            f.setVisible(true);
        }catch (Exception e){
            System.out.println("error "+e);
        }
    }//GEN-LAST:event_jButton5MouseClicked

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jComboBoxDiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxDiaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxDiaActionPerformed

    private void jButton7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton7MouseClicked
      resultadosInforme();
    }//GEN-LAST:event_jButton7MouseClicked

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton7ActionPerformed

    private void curvaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_curvaActionPerformed

        graficarinfectados();

    }//GEN-LAST:event_curvaActionPerformed

    private void curvarecuperadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_curvarecuperadosActionPerformed
        graficarrecuperados();
    }//GEN-LAST:event_curvarecuperadosActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        graficarfallecidos();
    }//GEN-LAST:event_jButton6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ResultMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ResultMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ResultMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ResultMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ResultMenu().setVisible(true);
            }
        });
    }
private void setFechaOEvento(){
        if (jRadioButtonPrimera.isSelected()) {
            setDatosPrimera();
        }
        if (jRadioButtonSegunda.isSelected()) {
            setDatosSegunda();
        }
        if (jRadioButtonTercera.isSelected()) {
            setDatosTercera();
        }
        if (jRadioButtonCuarta.isSelected()) {
            setDatosCuarta();
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel JLabelPersonasInfectadas;
    private javax.swing.JLabel JLabelPoblacion;
    private javax.swing.JLabel JLabelTiempo;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton curva;
    private javax.swing.JButton curvarecuperados;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButtonAceptar;
    private javax.swing.JButton jButtonSalir;
    private javax.swing.JButton jButtonVolver;
    private javax.swing.JComboBox<String> jComboBoxDia;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelContagiados;
    private javax.swing.JLabel jLabelContagio;
    private javax.swing.JLabel jLabelDistanciamientoo;
    private javax.swing.JLabel jLabelDuracion;
    private javax.swing.JLabel jLabelFallecidos;
    private javax.swing.JLabel jLabelFechaFinn;
    private javax.swing.JLabel jLabelFechaInicioo;
    private javax.swing.JLabel jLabelInfectadas;
    private javax.swing.JLabel jLabelInicialmenteInfectadoss;
    private javax.swing.JLabel jLabelInteraccion;
    private javax.swing.JLabel jLabelRecuperados;
    private javax.swing.JLabel jLabelRecuperadoss;
    private javax.swing.JLabel jLabelSusceptibles;
    private javax.swing.JLabel jLabelTiempoSimulacionn;
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JLabel jLabelTitulo1;
    private javax.swing.JLabel jLabelTitulo2;
    private javax.swing.JLabel jLabelTitulo3;
    private javax.swing.JLabel jLabelTitulo4;
    private javax.swing.JLabel jLabelTitulo5;
    private javax.swing.JLabel jLabelTotalContagiadoss;
    private javax.swing.JLabel jLabelTotalFallecidoss;
    private javax.swing.JLabel jLabelVacunacion;
    private javax.swing.JLabel jLabelVacunados;
    private javax.swing.JLabel jLabeltasaMortalidad;
    private javax.swing.JLabel jLabeltasaRecuperacion;
    private javax.swing.JRadioButton jRadioButtonCuarta;
    private javax.swing.JRadioButton jRadioButtonPrimera;
    private javax.swing.JRadioButton jRadioButtonSegunda;
    private javax.swing.JRadioButton jRadioButtonTercera;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    // End of variables declaration//GEN-END:variables
    
    
    public void resultado(){
        traerDatosSimulacion();
        simulacionSIRF();
        
        llenarjComboBoxDia();
        setResultadosFinales(totalContagiados, totalNoAfectados);
    }
    
    
    //Se realiza la simulacion tomando en cuenta la tasa de vacunacion ingresada por el usuario
    public void simulacionSIRF(){
        double time = tiempo; 
        double Poblacion = poblacion_total;
        infectados = personasInfectadas;
        susceptibles = Poblacion-infectados;
        double contagios;
        double interaccion=tasaInter;
        double probabilidadContagio = probabilidadCon;
        double recuperaciones;
        double fallecimientos;
        double tasaRecuperacion = tasaRec;
        double tasaMortalidad = tasaMor;
        double duracionMedia = duracionMed;
        double totalContagios, totalNoAfectados = 0, vacunaciones;
        
        
        for(int i=0; i<=time; i++){
            contagios = infectados*interaccion*susceptibles/(susceptibles+R+infectados)*probabilidadContagio;

            recuperaciones = infectados*tasaRecuperacion/duracionMedia;
            fallecimientos = infectados*tasaMortalidad/duracionMedia;
            vacunaciones = susceptibles*tasaVacunacion/duracionMedia;
            
            susceptibles = susceptibles - contagios - vacunaciones;
            infectados = infectados + contagios - recuperaciones - fallecimientos;
            R = R + recuperaciones;
            F = F + fallecimientos;
            vacunados = vacunados + vacunaciones;
           
            totalContagios = infectados + R + F;
            totalNoAfectados = Poblacion - totalContagios;
            
            totalContagiados = (int) Math.round(totalContagios);
            this.totalNoAfectados = (int) Math.round(totalNoAfectados);
            
           
             //curva
            curvainfectados.addValue(infectados, "infectados", i+"");
            curvarecu.addValue(R, "recuperados", i+"");
            curvafallecidos.addValue(F, "fallecidos", i+"");
            
                        //Añadimos el valor en cada arraylist
            contagiadosDia.add(Math.round(totalContagios) + "");
            infectadosDia.add(Math.round(infectados) + "");
            recuperadosDia.add(Math.round(R) + "");
            fallecidosDia.add(Math.round(F) + "");
            noAfectadosDia.add(Math.round(totalNoAfectados) + "");
            vacunadosDia.add(Math.round(vacunados) + ""); 
        }
        for(int j=0; j<= tiempo; j++){
             dias.add(j);
            }
    }
     public void graficarinfectados(){
        
        /*DefaultCategoryDataset dataset = new DefaultCategoryDataset();
        dataset.addValue(15, "infectados", "5");
        dataset.addValue(30, "infectados", "10");
        dataset.addValue(60, "Hospitales", "1990");
        dataset.addValue(120, "Hospitales", "2000");
        dataset.addValue(240, "Hospitales", "2010");
        dataset.addValue(150, "Hospitales", "2014");*/
 
        
        JFreeChart lineChart = ChartFactory.createLineChart(
                "Curva de infectados", 
                "Dias", 
                "Infectados", 
                curvainfectados,
                PlotOrientation.VERTICAL, true, true, false);
 
        
        ChartPanel panel = new ChartPanel(lineChart);
 
        
        
        // Creamos la ventana
        JFrame ventana = new JFrame("Curva");
        ventana.setVisible(true);
        ventana.setSize(800, 600);
        
 
        ventana.add(panel);
        
        
   }
    
    //Graficar la curva
    public void graficarrecuperados(){
        
        /*DefaultCategoryDataset dataset = new DefaultCategoryDataset();
        dataset.addValue(15, "infectados", "5");
        dataset.addValue(30, "infectados", "10");
        dataset.addValue(60, "Hospitales", "1990");
        dataset.addValue(120, "Hospitales", "2000");
        dataset.addValue(240, "Hospitales", "2010");
        dataset.addValue(150, "Hospitales", "2014");*/
 
        
        JFreeChart lineChart1 = ChartFactory.createLineChart(
                "Curva de recuperados", 
                "Dias", 
                "Recuperados", 
                curvarecu,
                PlotOrientation.VERTICAL, true, true, false);
 
        
        ChartPanel panel1 = new ChartPanel(lineChart1);
 
        
        
        // Creamos la ventana
        JFrame ventana = new JFrame("Curva");
        ventana.setVisible(true);
        ventana.setSize(800, 600);
        
 
        ventana.add(panel1);
        
   }
    
    //Graficar la curva
    public void graficarfallecidos(){
        
        /*DefaultCategoryDataset dataset = new DefaultCategoryDataset();
        dataset.addValue(15, "infectados", "5");
        dataset.addValue(30, "infectados", "10");
        dataset.addValue(60, "Hospitales", "1990");
        dataset.addValue(120, "Hospitales", "2000");
        dataset.addValue(240, "Hospitales", "2010");
        dataset.addValue(150, "Hospitales", "2014");*/
 
        
        JFreeChart lineChart2 = ChartFactory.createLineChart(
                "Curva de fallecidos", 
                "Dias", 
                "Fallecidos", 
                curvafallecidos,
                PlotOrientation.VERTICAL, true, true, false);
 
        
        ChartPanel panel2 = new ChartPanel(lineChart2);
 
        
        
        // Creamos la ventana
        JFrame ventana = new JFrame("Curva");
        ventana.setVisible(true);
        ventana.setSize(800, 600);
        
 
        ventana.add(panel2);
        
   }
    //Buscamos el dia seleccionado por el usuario segun el comboBox
    private void buscarDia() {
        String diaSeleccionado = jComboBoxDia.getSelectedItem().toString();
        int dia = Integer.parseInt(diaSeleccionado);
        seleccionarDia(dia);
    }

    //Buscamos el dia seleccionado en los arraylist
    private void seleccionarDia(int dia) {
        jLabelSusceptibles.setText(noAfectadosDia.get(dia) + "");
        jLabelContagiados.setText(contagiadosDia.get(dia) + "");
        jLabelRecuperados.setText(recuperadosDia.get(dia) + "");
        jLabelFallecidos.setText(fallecidosDia.get(dia) + "");
        jLabelInfectadas.setText(infectadosDia.get(dia) + "");
        jLabelVacunados.setText(vacunadosDia.get(dia) + "");
    }
    
    //Llenamos el combobox con la cantidad de dias ingresadas por el usuario
    private void llenarjComboBoxDia(){
        jComboBoxDia.removeAllItems();
        for (int i = 1; i < tiempo; i++) {
            jComboBoxDia.addItem(i + "");
        }
    }

    //Trae los datos ingresados por el usuario localizados en una clase con una unica instancia
    private void traerDatosSimulacion() {
        DatosSimulacion datosSimulacion = DatosSimulacion.getDatosSimulacion();
        
        poblacion_total = datosSimulacion.getCantidadPoblacion();
        personasInfectadas = datosSimulacion.getCantidadPersonasInfectadas();
        tiempo = datosSimulacion.getTiempoSimulacion();
        tasaInter = datosSimulacion.getTasaInteraccion();
        probabilidadCon = datosSimulacion.getProbabilidadContagio();
        tasaRec = datosSimulacion.getTasaRecuperacion();
        tasaMor = datosSimulacion.getTasaMortalidad();
        duracionMed = datosSimulacion.getDuracionMedia();
        tasaVacunacion = datosSimulacion.getTasaVacunacion();
    }
    
    //Ingresamos los resultados finales al Singleton de resultados finales
    private void setResultadosFinales(int contagiados, int noAfectados){
        ResultadosSimulacion resultados = ResultadosSimulacion.getResultadosSimulacion();
        resultados.setTotalContagiados(contagiados);
        resultados.setInfectados(Math.round(infectados));
        resultados.setRecuperados(Math.round(R));
        resultados.setFallecidos(Math.round(F));
        resultados.setVacunados(Math.round(vacunados));
        resultados.setNoAfectados(noAfectados);
    }


     public void Cuarentena(){
        
        double time = tiempo; 
        //double time = 20;
        double Poblacion = poblacion_total; 
        //double Poblacion = 100;
        infectados = personasInfectadas;
        //double infectados = 1;
        susceptibles = poblacion_total-personasInfectadas; 
//        double susceptibles = Poblacion-infectados;
        R = 0;
        F = 0;
        double contagios;
        double interaccion=2.5;
        double a = 0.14;
        double recuperaciones;
        double fallecimientos;
        double hospitalizados;
        double tasaRecuperacion = 0.95;
        double tasaMortalidad = 0.05;
        double tasaHospital = 0.04;
        int duracionMedia = 12;
        
        for(int i=0; i<time; i++){
            
            contagios = (1-tasaHospital)*infectados*interaccion*susceptibles/(susceptibles+R+infectados)*a;

            susceptibles = susceptibles - contagios;
            
            recuperaciones = infectados*tasaRecuperacion*(1+tasaHospital)/duracionMedia;
            fallecimientos = infectados*tasaMortalidad*(1+tasaHospital)/duracionMedia;
            
            infectados = infectados + contagios - recuperaciones - fallecimientos;
            R = R + recuperaciones;
            F = F + fallecimientos;
            hospitalizados = tasaHospital*infectados;
            
        }
        
    }
    
    public void Vacunacion(){
        
        //double time = tiempo; 
       /* double time = 20;
        //double Poblacion = poblacion_total; 
        double Poblacion = 100;
        //infectados = personasInfectadas;
        double infectados = 1;
       //susceptibles = poblacion_total-personasInfectadas; 
        double susceptibles = Poblacion-infectados;
        double R = 0;
        double F = 0;
        double contagios;
        double interaccion=2.5;
        double a = 0.14;
        double recuperaciones;
        double fallecimientos;
        double hospitalizados;
        double tasaRecuperacion = 0.95;
        double tasaMortalidad = 0.05;
        double tasaHospital = 0.04;
        int duracionMedia = 12;
        
        for(int i=0; i<time; i++){
            
            contagios = (1-tasaHospital)*infectados*interaccion*susceptibles/(susceptibles+R+infectados)*a;

            susceptibles = susceptibles - contagios;
            
            recuperaciones = infectados*tasaRecuperacion*(1+tasaHospital)/duracionMedia;
            fallecimientos = infectados*tasaMortalidad*(1+tasaHospital)/duracionMedia;
            
            infectados = infectados + contagios - recuperaciones - fallecimientos;
            R = R + recuperaciones;
            F = F + fallecimientos;
            hospitalizados = tasaHospital*infectados;
            
        }
        */
    }
     private void setDatosPrimera() {
        fechaInicioo = "17 de marzo";
        fechaFinn = "31 de mayo";
        inicialmenteInfectadoss = "1";
        tiempoSimulacionn = "78 días";
        distanciamientoo = "Cuarentena rígida";
        totalContagiadoss = "556";
        totalFallecidoss = "23";
        recuperadoss = "";
    }

    private void setDatosSegunda() {
        fechaInicioo = "01 de junio";
        fechaFinn = "20 de junio";
        inicialmenteInfectadoss = "556";
        tiempoSimulacionn = "20 días";
        distanciamientoo = "Cuarentena dinámica";
        totalContagiadoss = "2302";
        totalFallecidoss = "125";
        recuperadoss = "";
    }

    private void setDatosTercera() {
        fechaInicioo = "24 de junio";
        fechaFinn = "11 de julio";
        inicialmenteInfectadoss = "2302";
        tiempoSimulacionn = "17 días";
        distanciamientoo = "Cuarentena rígida";
        totalContagiadoss = "5014";
        totalFallecidoss = "";
        recuperadoss = "";
    }

    private void setDatosCuarta() {
        fechaInicioo = "13 de julio";
        fechaFinn = "03 de agosto";
        inicialmenteInfectadoss = "5014";
        tiempoSimulacionn = "22 días";
        distanciamientoo = "Cuarentena mixta";
        totalContagiadoss = "6526";
        totalFallecidoss= "498";
        recuperadoss = "1320";
    }
    
    private void setCampos(){
        jLabelFechaInicioo.setText(fechaInicioo + "");
        jLabelFechaFinn.setText(fechaFinn + "");
        jLabelInicialmenteInfectadoss.setText(inicialmenteInfectadoss + "");
        jLabelTiempoSimulacionn.setText(tiempoSimulacionn + "");
        jLabelDistanciamientoo.setText(distanciamientoo + "");
        jLabelTotalContagiadoss.setText(totalContagiadoss + "");
        jLabelTotalFallecidoss.setText(totalFallecidoss + "");
        jLabelRecuperadoss.setText(recuperadoss + "");
    }
    
    
     public void resultadosInforme(){
  try{
    /*  Object [] opciones = {"ACEPTAR","CANCELAR"};
      int eleccion = JOptionPane.showOptionDialog(null,
              "Se generará un reporte, ¿Desea Continuar?", "Mensaje de Confirmacion",
              JOptionPane.YES_NO_OPTION,
              JOptionPane.QUESTION_MESSAGE,null,opciones,"Aceptar");
      
      if(eleccion == JOptionPane.YES_OPTION){*/
      String master = System.getProperty("user.dir")+ "/src/Reportes/Reporte1.jasper";
      HashMap parametros = new HashMap(); 
      parametros.put("poblacion",Math.round(poblacion_total) + " personas(s)");
      parametros.put("tiempoSimu",Math.round(tiempo) + " días");
      parametros.put("personasInfectadas",Math.round(personasInfectadas) + " persona(s)");
      parametros.put("tasaInteraccion",Math.round(tasaInter) + " persona(s)");
      parametros.put("tasaMortalidad",Math.round(tasaMor*100) + " %");
      parametros.put("duracionMedia",Math.round(duracionMed) + " dias");
      parametros.put("probContagio",Math.round(probabilidadCon*100) + " %");
      parametros.put("tasaRecuperacion",Math.round(tasaRec*100) + " %");
      if(tasaVacunacion != 0){
          parametros.put("tasaVacunacion",tasaVacunacion*100 + " %");
        }
        else{
          parametros.put("tasaVacunacion","No existe");
        }
     
        parametros.put("poblacionContagiada",totalContagiados + " persona(s)");
        parametros.put("poblacionInfectada",Math.round(infectados) + " personas(s)");
        parametros.put("poblacionRecuperada",Math.round(R) + " persona(s)");
        parametros.put("poblacionFallecida",Math.round(F) + " personas(s)");
        parametros.put("poblacionVacunada",Math.round(vacunados) + " persona(s)");
        parametros.put("poblacionNoAfectada",totalNoAfectados + " persona(s)");
        

        parametros.put("cantContagiada",totalContagiados);
        parametros.put("cantInfectados", Math.round(infectados));
        parametros.put("cantRecuperados", Math.round(R) );
        parametros.put("cantFallecidos", Math.round(F));
        parametros.put("cantVacunados", Math.round(vacunados));
        
        //parametros.put("prueba",contagiadosDia);
        
         parametros.put("parameter1",infectadosDia);
         parametros.put("parameter2",recuperadosDia);
         parametros.put("parameter3",fallecidosDia);
         parametros.put("parameter4",vacunadosDia);
         parametros.put("parameter5",dias);
       // JRBeanCollectionDataSource ds = new JRBeanCollectionDataSource(contagiadosDia);
        //parametros.put("ds",ds);
      
      JasperPrint informe = JasperFillManager.fillReport(master,parametros,new JREmptyDataSource());
      JasperViewer.viewReport(informe, false);
      
      }catch (Exception e){
      JOptionPane.showMessageDialog(null, "Error General Lanzando Reporte"+e.getMessage().toString());
      }
     }
   
}
    


